export const projects = [
  {
    title: '5G X LiFi',
    description: "",
      image: '/images/5G X LiFi/Images/Darker Hero-05.jpg',
      tags: ['Product'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: '',
    description: "",
      image: '/images/white.jpg',
      tags: [],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: '',
    description: "",
      image: '/images/white.jpg',
      tags: [],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'Cornetto',
    description:"",
    image: '/images/Cornetto/Images/Antarctic Icon.png',
    tags: ['Branding'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: '1 Family 1 Room',
    description: "",
      image: '/images/PDR Lunchbox/Images/PDR Lunchbox-16.jpg',
      tags: ['Empathy'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: '',
    description: "",
      image: '/images/white.jpg',
      tags: [],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: '',
    description: "",
      image: '/images/white.jpg',
      tags: [],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Sight',
    description: "",
    image: '/images/Sight/Images/Buttons.png',
    tags: ['Product'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'Homedock',
    description: "",
    image: '/images/Home Dock/Images/Hero.png',
    tags: ['Product'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 4,
  },
];