export const projects = [
  {
    title: '5G X LiFi',
    description: "",
      image: '/images/5GXLiFi.jpg',
      tags: ['Product'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: '',
    description: "",
      image: '/images/white.jpg',
      tags: [],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: '',
    description: "",
      image: '/images/white.jpg',
      tags: [],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'Cornetto',
    description:"",
    image: '/images/Cornetto.jpg',
    tags: ['Branding'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: '1 Family 1 Room',
    description: "",
      image: '/images/1Family1Room.jpg',
      tags: ['Empathy'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: '',
    description: "",
      image: '/images/white.jpg',
      tags: [],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: '',
    description: "",
      image: '/images/white.jpg',
      tags: [],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Sight',
    description: "",
    image: '/images/Sight.jpg',
    tags: ['Product'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'Homedock',
    description: "",
    image: '/images/Homedock.jpg',
    tags: ['Product'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 4,
  },
];